const dadosPorJogo = {
    "Digimon TCG": {
        exemploNome: "Agumon",
        exemploNumero: "BT1-010",
        colecoes: [
            "Rebirth of Tamers (BT01)",
            "Ultimate Power (BT02)",
            "Union Impact (BT03)",
            "Great Legend (BT04)",
            "Battle of Omega (BT05)",
            "Double Diamond (BT06)"
        ]
    },
    "Dragon Ball Fusion World": {
        exemploNome: "Son Goku",
        exemploNumero: "FB01-001",
        colecoes: [
            "Awakened Pulse (FB01)",
            "Blazing Aura (FB02)",
            "Raging Roar (FB03)",
            "Ultra Limit (FB04)",
            "New Adventure (FB05)",
            "Rivals Clash (FB06)",
            "Wish for Shenron (FB07)",
            "Saiyan's Pride (FB08)",
            "Dual Evolution (FB09)",
            "Cross Force (FB10)",
            "Manga Booster 01 (SB01)",
            "Manga Booster 02 (SB02)",
            "Story Booster 01 (ST01)",
            "Promotion Card (FP)",
            "Son Goku (FS01)",
            "Vegeta (FS02)",
            "Broly (FS03)",
            "Frieza (FS04)",
            "Bardock (FS05)",
            "Son Goku (Mini) (FS06)",
            "Vegeta (Mini) (FS07)",
            "Vegeta (Mini) Super Saiyan 3 (FS08)",
            "EX Shallot (FS09)",
            "EX Giblet (FS10)",
            "EX The Phase of Evolution (FS11)",
            "EX The Beat of Ki (FS12)"
        ]
    },
    "Flesh and Blood": {
        exemploNome: "Bravo, Showstopper",
        exemploNumero: "WTR001",
        colecoes: [
            "Welcome to Rathe",
            "Arcane Rising",
            "Crucible of War",
            "Monarch",
            "Tales of Aria",
            "Everfest",
            "Uprising",
            "Dusk till Dawn",
            "Heavy Hitters"
        ]
    },
     "Gundam TCG": {
        exemploNome: "RX-78-2 Gundam",
        exemploNumero: "GD01-001",
        colecoes: [
            "Newtype Rising (GD01)",
            "Dual Impact (GD02)",
            "Steel Requiem (GD03)",
            "Phantom Aria (GD04)",
            "Freedom Ascention (GD05)",
            "Heroic Beginnings (ST01)",
            "Wings of Advance (ST02)",
            "Zeon's Rush (ST03)",
            "SEED Strike (ST04)",
            "Iron Bloom (ST05)",
            "Clan Unity (ST06)",
            "Celestial Drive (ST07)",
            "Flash of Radiance (ST08)",
            "Destiny Ignition (ST09)",
            "Generation Pulse (ST10)",
            "Eternal Nexus (EB01)",
            "Deck Build Box Freedom Ascention (SC01)",
            "Promotion Card (P)"
        ]
    },
    "Lorcana TCG": {
        exemploNome: "Elsa - Spirit of Winter",
        exemploNumero: "001/204 EN 1",
        colecoes: [
            "The First Chapter (Set 1)",
            "Rise of the Floodborn (Set 2)",
            "Into the Inklands (Set 3)",
            "Ursula's Return (Set 4)",
            "Shimmering Skies (Set 5)",
            "Azurite Sea (Set 6)",
            "Archazia's Island (Set 7)",
            "Reign of Jafar (Set 8)",
            "Fabled (Set 9)",
            "Whispers in the Well (Set 10)",
            "Winterspell (Set 11)",
            "Wilds Unknown (Set 12)",
            "Attack of the Vine! (Set 13)"
        ]
    },    
    "Magic: The Gathering": {
        exemploNome: "Black Lotus",
        exemploNumero: "232",
        colecoes: [
            "Alpha / Beta",
            "Unlimited",
            "Revised",
            "Modern Horizons 3",
            "Bloomburrow",
            "Duskmourn: House of Horror",
            "Innistrad",
            "Ravnica Remastered"
        ]
    },
    "One Piece TCG": {
        exemploNome: "Monkey D. Luffy",
        exemploNumero: "OP01-003",
        colecoes: [
            "Romance Dawn (OP01)",
            "Paramount War (OP02)",
            "Pillars of Strength (OP03)",
            "Kingdoms of Intrigue (OP04)",
            "Awakening of the New Era (OP05)",
            "Wings of the Captain (OP06)",
            "500 Years in the Future (OP07)",
            "Two Legends (OP08)",
            "Emperors in the New Wolrd (OP09)",
            "Royal Blood (OP10)",
            "A Fist of Divine Speed (OP11)",
            "Legacy of the Master (OP12)",
            "Carrying on his Will (OP13)",
            "The Azure Sea's Seven (OP14-EB04)",
            "Adventure on Kami's Island (OP15-EB04)",
            "The Time of Battle (OP16)",
            "Memorial Collection (EB01)",
            "Anime 25th Collection (EB02)",
            "One Piece Heroines Edition (EB03)",
            "One Piece The Best (PRB01)",
            "One Piece The Best Vol. 2 (PRB02)",
            "Promotion Card (P)",
            "Straw Hat Crew (ST01)",
            "Worst Generation (ST02)",
            "The Seven Warlords of the Sea (ST03)",
            "Animal Kingdom Pirates (ST04)",
            "One Piece Film Edition (ST05)",
            "Absolute Justice (ST06)",
            "Big Mom Pirates (ST07)",
            "Monkey.D.Luffy (ST08)",
            "Yamato (ST09)",
            "Ultra Deck The Three Captains (ST10)",
            "Uta (ST11)",
            "Zoro and Sanji (ST12)",
            "Ultra Deck The Three Brothers (ST13)",
            "3D2Y (ST14)",
            "Red Edward.Newgate (ST15)",
            "Green Uta (ST16)",
            "Blue Donquixote Doflamingo (ST17)",
            "Purple Monkey.D.Luffy (ST18)",
            "Black Smoker (ST19)",
            "Yellow Charlotte Katakuri (ST20)",
            "EX GEAR5 (ST21)",
            "Ace & Newgate (ST22)",
            "RED Shanks (ST23)",
            "GREEN Jewelry Bonney (ST24)",
            "BLUE Buggy (ST25)",
            "PURPLE/BLACK Monkey.D.Luffy (ST26)",
            "BLACK Marshall.D.Teach (ST27)",
            "GREEN/YELLOW Yamato (ST28)",
            "Egghead (ST29)",
            "Luffy & Ace (ST30)",
            "RED Monkey.D.Luffy (ST31)",
            "GREEN Roronoa Zoro (ST32)",
            "BLUE Kuzan (ST33)",
            "PURPLE Charlotte Katakuri (ST34)",
            "RED/BLACK Sabo (ST35)",
            "YELLOW Eustass'Captain'Kid (ST36)"
        ]
    },
    "Pokémon TCG": {
        exemploNome: "Charizard",
        exemploNumero: "4/102",
        colecoes: [
            "Base Set (BS)",
            "Jungle (JU)",
            "Fossil (FO)",
            "Base Set 2 (B2)",
            "Team Rocket (TR)",
            "Gym Heroes (G1)",
            "Gym Challenge (G2)",
            "Neo Genesis (N1)",
            "Neo Discovery (N2)",
            "Neo Revelation (N3)",
            "Neo Destiny (N4)",
            "Legendary Collection (LC)",
            "EX Ruby & Sapphire (RS)",
            "EX Sandstorm (SS)",
            "EX Dragon (DR)",
            "EX Team Magma vs Team Aqua (MA)",
            "EX Hidden Legends (HL)",
            "EX FireRed & LeafGreen (RG)",
            "EX Team Rocket Returns (TRR)",
            "EX Deoxys (DX)",
            "EX Emerald (EM)",
            "EX Unseen Forces (UF)",
            "EX Delta Species (DS)",
            "EX Legend Maker (LM)",
            "EX Holon Phantoms (HP)",
            "EX Crystal Guardians (CG)",
            "EX Dragon Frontiers (DF)",
            "EX Power Keepers (PK)",
            "Scarlet & Violet (SVI)",
            "Paldea Evolved (PAL)",
            "Obsidian Flames (OBF)",
            "Pokémon 151 (MEW)",
            "Surging Sparks (SSP)",
        ]
    },
    "Riftbound TCG": {
        exemploNome: "Aethelgard Vanguard",
        exemploNumero: "RB01-001",
        colecoes: [
            "Origins (OGN)",
            "Spiritforged (SFD)",
            "Unleashed (UNL)",
            "Vendetta (VEN)"
        ]
    }
};