const dadosPorJogo = {
    "Digimon": {
        exemploNome: "Agumon",
        exemploNumero: "BT1-010",
        colecoes: [
            "Rebirth of Tamers (BT01)",
            "Ultimate Power (BT02)",
            "Union Impact (BT03)",
            "Great Legend (BT04)",
            "Battle of Omega (BT05)",
            "Double Diamond (BT06)"
        ]
    },
    "Dragon Ball Fusion World": {
        exemploNome: "Son Goku",
        exemploNumero: "FB01-001",
        colecoes: [
            {nome:"FB01 - Awakened Pulse", ano: 2024},
            {nome:"FB02 - Blazing Aura", ano: 2024},
            {nome:"FB03 - Raging Roar", ano: 2024},
            {nome:"FB04 - Ultra Limit", ano: 2024},
            {nome:"FB05 - New Adventure", ano: 2025},
            {nome:"FB06 - Rivals Clash", ano: 2025},
            {nome:"FB07 - Wish for Shenron", ano: 2025},
            {nome:"FB08 - Saiyan's Pride", ano: 2025},
            {nome:"FB09 - Dual Evolution", ano: 2026},
            {nome:"FB10 - Cross Force", ano: 2026},
            {nome:"SB01 - Manga Booster 01", ano: 2025},
            {nome:"SB02 - Manga Booster 02", ano: 2025},
            {nome:"ST01 - Story Booster 01", ano: 2026},
            {nome:"FP - Promotion Card", ano: 2024},
            {nome:"FS01 - Son Goku", ano: 2024},
            {nome:"FS02 - Vegeta", ano: 2024},
            {nome:"FS03 - Broly", ano: 2024},
            {nome:"FS04 - Frieza", ano: 2024},
            {nome:"FS05 - Bardock", ano: 2024},
            {nome:"FS06 - Son Goku (Mini)", ano: 2024},
            {nome:"FS07 - Vegeta (Mini)", ano: 2024},
            {nome:"FS08 - Vegeta (Mini) Super Saiyan 3", ano: 2025},
            {nome:"FS09 - EX Shallot", ano: 2025},
            {nome:"FS10 - EX Giblet", ano: 2025},
            {nome:"FS11 - EX The Phase of Evolution", ano: 2026},
            {nome:"FS12 - EX The Beat of Ki", ano: 2026}
        ]
    },
    "Flesh and Blood": {
        exemploNome: "Bravo, Showstopper",
        exemploNumero: "WTR001",
        colecoes: [
            {nome: "Welcome to Rathe", ano: 2019},
            {nome: "Arcane Rising", ano: 2020},
            {nome: "Crucible of War", ano: 2020},
            {nome: "Monarch", ano: 2021},
            {nome: "Tales of Aria", ano: 2021},
            {nome: "Everfest", ano: 2022},
            {nome: "History Pack 1", ano: 2022},
            {nome: "Uprising", ano: 2022},
            {nome: "Disnaty", ano: 2022},
            {nome: "Outsiders", ano: 2023},
            {nome: "Dusk till Dawn", ano: 2023},
            {nome: "Bright Lights", ano: 2023},
            {nome: "Heavy Hitters", ano: 2024},
            {nome: "Part the Mistveil", ano: 2024},
            {nome: "Rosetta", ano: 2024},
            {nome: "The Hunted", ano: 2025},
            {nome: "High Seas", ano: 2025},
            {nome: "Mastery Pack Guardian", ano: 2025},
            {nome: "Super Slam", ano: 2025},
            {nome: "Compendium of Rathe", ano: 2026},
            {nome: "Omens of the Third Age", ano: 2026}
        ]
    },
     "Gundam": {
        exemploNome: "RX-78-2 Gundam",
        exemploNumero: "GD01-001",
        colecoes: [
            {nome: "GD01 - Newtype Rising", ano: 2025},
            {nome: "GD02 - Dual Impact", ano: 2025},
            {nome: "GD03 - Steel Requiem", ano: 2026},
            {nome: "GD04 - Phantom Aria", ano: 2026},
            {nome: "GD05 - Freedom Ascention", ano: 2026},
            {nome: "ST01 - Heroic Beginnings", ano: 2025},
            {nome: "ST02 - Wings of Advance", ano: 2025},
            {nome: "ST03 - Zeon's Rush", ano: 2025},
            {nome: "ST04 - SEED Strike", ano: 2025},
            {nome: "ST05 - Iron Bloom", ano: 2025},
            {nome: "ST06 - Clan Unity", ano: 2025},
            {nome: "ST07 - Celestial Drive", ano: 2026},
            {nome: "ST08 - Flash of Radiance", ano: 2026},
            {nome: "ST09 - Destiny Ignition", ano: 2026},
            {nome: "ST10 - Generation Pulse", ano: 2026},
            {nome: "EB01 - Eternal Nexus", ano: 2026},
            {nome: "SC01 - Deck Build Box Freedom Ascention", ano: 2026},
            {nome: "P - Promotion Card", ano: 2024}
        ]
    },
    "Lorcana": {
        exemploNome: "Elsa - Spirit of Winter",
        exemploNumero: "001/204 EN 1",
        colecoes: [
            {nome: "Set 1 -The First Chapter", ano: 2023},
            {nome: "Set 2 -Rise of the Floodborn", ano: 2023},
            {nome: "Set 3 -Into the Inklands", ano: 2023},
            {nome: "Set 4 -Ursula's Return", ano: 2024},
            {nome: "Set 5 -Shimmering Skies", ano: 2024},
            {nome: "Set 6 -Azurite Sea", ano: 2024},
            {nome: "Set 7 -Archazia's Island", ano: 2025},
            {nome: "Set 8 -Reign of Jafar", ano: 2025},
            {nome: "Set 9 -Fabled", ano: 2025},
            {nome: "Set 10 -Whispers in the Well", ano: 2025},
            {nome: "Set 11 -Winterspell", ano: 2026},
            {nome: "Set 12 -Wilds Unknown", ano: 2026},
            {nome: "Set 13 -Attack of the Vine!", ano: 2026}
        ]
    },    
    "Magic: The Gathering": {
        exemploNome: "Black Lotus",
        exemploNumero: "232",
        colecoes: [
            "Alpha / Beta",
            "Unlimited",
            "Revised",
            "Modern Horizons 3",
            "Bloomburrow",
            "Duskmourn: House of Horror",
            "Innistrad",
            "Ravnica Remastered"
        ]
    },
    "One Piece": {
        exemploNome: "Monkey D. Luffy",
        exemploNumero: "OP01-003",
        colecoes: [
            {nome: "OP01 - Romance Dawn", ano: 2022},
            {nome: "OP02 - Paramount War", ano: 2023},
            {nome: "OP03 - Pillars of Strength", ano: 2023},
            {nome: "OP04 - Kingdoms of Intrigue", ano: 2023},
            {nome: "OP05 - Awakening of the New Era", ano: 2023},
            {nome: "OP06 - Wings of the Captain", ano: 2024},
            {nome: "OP07 - 500 Years in the Future", ano: 2024},
            {nome: "OP08 - Two Legends", ano: 2024},
            {nome: "OP09 - Emperors in the New World", ano: 2024},
            {nome: "OP10 - Royal Blood", ano: 2025},
            {nome: "OP11 - A Fist of Divine Speed", ano: 2025},
            {nome: "OP12 - Legacy of the Master", ano: 2025},
            {nome: "OP13 - Carrying on his Will", ano: 2025},
            {nome: "OP14 - The Azure Sea's Seven", ano: 2026},
            {nome: "OP15 - Adventure on Kami's Island", ano: 2026},
            {nome: "OP16 - The Time of Battle", ano: 2026},
            {nome: "EB01 - Memorial Collection", ano: 2024},
            {nome: "EB02 - Anime 25th Collection", ano: 2025},
            {nome: "EB03 - One Piece Heroines Edition", ano: 2026},
            {nome: "PRB01 - One Piece The Best", ano: 2024},
            {nome: "PRB02 - One Piece The Best Vol. 2", ano: 2025},
            {nome: "P - Promotion Card", ano: 2022},
            {nome: "ST01 - Straw Hat Crew", ano: 2022},
            {nome: "ST02 - Worst Generation", ano: 2022},
            {nome: "ST03 - The Seven Warlords of the Sea", ano: 2022},
            {nome: "ST04 - Animal Kingdom Pirates", ano: 2022},
            {nome: "ST05 - One Piece Film Edition", ano: 2023},
            {nome: "ST06 - Absolute Justice", ano: 2023},
            {nome: "ST07 - Big Mom Pirates", ano: 2023},
            {nome: "ST08 - Monkey.D.Luffy", ano: 2023},
            {nome: "ST09 - Yamato", ano: 2023},
            {nome: "ST10 - Ultra Deck The Three Captains", ano: 2023},
            {nome: "ST11 - Uta", ano: 2024},
            {nome: "ST12 - Zoro and Sanji", ano: 2024},
            {nome: "ST13 - Ultra Deck The Three Brothers", ano: 2024},
            {nome: "ST14 - 3D2Y", ano: 2024},
            {nome: "ST15 - Red Edward.Newgate", ano: 2024},
            {nome: "ST16 - Green Uta", ano: 2024},
            {nome: "ST17 - Blue Donquixote Doflamingo", ano: 2024},
            {nome: "ST18 - Purple Monkey.D.Luffy", ano: 2024},
            {nome: "ST19 - Black Smoker", ano: 2024},
            {nome: "ST20 - Yellow Charlotte Katakuri", ano: 2024},
            {nome: "ST21 - EX GEAR5", ano: 2025},
            {nome: "ST22 - Ace & Newgate", ano: 2025},
            {nome: "ST23 - RED Shanks", ano: 2025},
            {nome: "ST24 - GREEN Jewelry Bonney", ano: 2025},
            {nome: "ST25 - BLUE Buggy", ano: 2025},
            {nome: "ST26 - PURPLE/BLACK Monkey.D.Luffy", ano: 2025},
            {nome: "ST27 - BLACK Marshall.D.Teach", ano: 2025},
            {nome: "ST28 - GREEN/YELLOW Yamato", ano: 2025},
            {nome: "ST29 - Egghead", ano: 2026},
            {nome: "ST30 - Luffy & Ace", ano: 2026},
            {nome: "ST31 - RED Monkey.D.Luffy", ano: 2026},
            {nome: "ST32 - GREEN Roronoa Zoro", ano: 2026},
            {nome: "ST33 - BLUE Kuzan", ano: 2026},
            {nome: "ST34 - PURPLE Charlotte Katakuri", ano: 2026},
            {nome: "ST35 - RED/BLACK Sabo", ano: 2026},
            {nome: "ST36 - YELLOW Eustass'Captain'Kid", ano: 2026}
        ]
    },
    "Pokémon": {
        exemploNome: "Charizard",
        exemploNumero: "4/102",
        colecoes: [
            "BS - Base Set",
            "JU - Jungle",
            "FO - Fossil",
            "B2 - Base Set 2",
            "TR - Team Rocket",
            "G1 - Gym Heroes",
            "G2 - Gym Challenge",
            "N1 - Neo Genesis",
            "N2 - Neo Discovery",
            "N3 - Neo Revelation",
            "N4 - Neo Destiny",
            "LC - Legendary Collection",
            "RS - EX Ruby & Sapphire",
            "SS - EX Sandstorm",
            "DR - EX Dragon",
            "MA - EX Team Magma vs Team Aqua",
            "HL - EX Hidden Legends",
            "RG - EX FireRed & LeafGreen",
            "TRR - EX Team Rocket Returns",
            "DX - EX Deoxys",
            "EM - EX Emerald",
            "UF - EX Unseen Forces",
            "DS - EX Delta Species",
            "LM - EX Legend Maker",
            "HP - EX Holon Phantoms",
            "CG - EX Crystal Guardians",
            "DF - EX Dragon Frontiers",
            "PK - EX Power Keepers",
            "SVI - Scarlet & Violet",
            "PAL - Paldea Evolved (PAL)",
            "OBF - Obsidian Flames (OBF)",
            "MEW - Pokémon 151 (MEW)",
            "SSP - Surging Sparks (SSP)",
        ]
    },
    "Riftbound TCG": {
        exemploNome: "Aethelgard Vanguard",
        exemploNumero: "RB01-001",
        colecoes: [
            {nome: "OGN - Origins", ano: 2025},
            {nome: "SFD - Spiritforged", ano: 2026},
            {nome: "UNL - Unleashed", ano: 2026},
            {nome: "VEN - Vendetta", ano: 2026}
        ]
    }
};